### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by lucky110125** [bcgsc/pavfinder#11]
Hello, I encountered some problems while interpreting the output file. I'm not sure about the meaning of some columns. For example, is the "spanning_reads" means the number of reads that support the mutation? And I don know how to get the varients frequence of each mutation.
Thank you.

**Comment by readmanchiu** [comment]
You are looking at the fusion output, "sv.bedpe", right? Yes, "spanning_reads" is the number of reads that span the fusion junction with at least 4bp on either side. The last column "flanking_pairs" is the number of read pairs that flank the junctions, but the reads themselves do not "touch" the junction. Each flanking_pair implies there is a fragment that crosses the junction. Since the two are mutually exclusive, so you can add the two columns up to come up with an estimate of the number of cDNA/RNA fragments that support the fusion.

PAVFinder does not report variant frequency, unfortunately. An indirect way of calculating it would be to run `map_splice.py` as I suggested in the previous issue, and interrogate the `junctions.bed` output. The 5th column reports the number of reads spanning each junction, so you can get an estimate of the abundance of the annotated junctions in the 2 fusion genes, and, using the fusion support from above, calculate the variant frequency in whatever definition you decide.

Hope this helps, let me know if you need more clarification or help.

**Comment by readmanchiu** [comment]
I'm closing this right now, @yanlina0205 
If there is anything I can do for you, please let me know.
